data_path:
  evaluation_data: /opt/ml/input/data/train_dataset
  root: /opt/ml/input/data
  training_data: /opt/ml/input/data/eval_dataset
save_path:
  checkpoints_path: ./results/checkpoint
  log_path: ./results/log
  root: ./results
  tensorboard_log_path: ./results/tensorboard
training_base:
  hyperparameters:
    args:
      learning_rate: 5.0e-05
      num_train_epochs: 5
      per_device_train_batch_size: 16
      warmup_steps: 500
      weight_decay: 0.01
    model:
      name: bert-base-multilingual-cased
      type: Bert
    seed: 327459
  trainee_name: baseline_trainee
  trainee_type: BaselineTrainee
trainings:
- {}
